In [1]:
# Import the needed libraries
import numpy as np

**72. How to swap two rows of an array?** 

In [44]:
# n is the length of the array
def row_swaper(n):
    x = np.random.randint(n, size = (2, n))
    print(f"The generated array is:\n{x}")
    print("\n")
    # Here's where comes the swapping magic
    x[[0, 1]] = x[[1, 0]]
    return f"The swapped array is:\n{x}"

print(row_swaper(10))

The generated array is:
[[7 5 2 4 5 8 9 5 8 4]
 [4 9 7 4 8 0 5 5 3 5]]


The swapped array is:
[[4 9 7 4 8 0 5 5 3 5]
 [7 5 2 4 5 8 9 5 8 4]]


**75. How to compute averages using a sliding window over an array?**

In [126]:
def moving_average(len_x, len_y):
    x = np.random.randint(len_x)
    y = np.random.randint(len_y)
    print(x, y)
    # valid is given for overlaping elements
    return np.convolve(x, y, 'valid')

print(moving_average(10, 10))

2 2
[4]
